FROM python:3.12-slim

COPY src/requirements_common.txt /requirements_common.txt
COPY src/requirements_100.txt /requirements.txt
RUN pip install -r /requirements_common.txt
RUN pip install -r /requirements.txt

COPY src/generate/generate_common.py /app/
COPY src/generate/generate_100.py /app/generate.py
